### ISSUE TITLE
Loss Module

### ISSUE THREAD

**Issue by YoungJoongUNC** [YapengTian/TDAN-VSR#13]
While I was trying to run the train.py, I faced the following error, because their is no loss code. Could you provide the loss code?

Thank you.

Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from loss import get_loss_fn
ModuleNotFoundError: No module named 'loss'

**Comment by YapengTian** [comment]
Sorry, the code is not fully ready since I am working on incoming ddls. I have added the loss function and slightly modified the train.py. I used the Temple sequence from SPMCs set https://github.com/jiangsutx/SPMC_VideoSR as validation set.

**Comment by YoungJoongUNC** [comment]
Thank you for your fast reply :)

**Comment by YoungJoongUNC** [comment]
Also, may I ask if you could upload the SR_datasets.py? train.py refers to it.

train.py
line 5: from SR_datasets import *

**Comment by YapengTian** [comment]
Yes, I have added it. Please check the SR_datasets.py.

**Comment by YoungJoongUNC** [comment]
Thank you so much for the fast feedback :D

**Comment by YapengTian** [comment]
Sorry for the inconvenience.
